# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FL_UPDATE_APP_IDENTIFIER"] = ENV["APP_IDENTIFIER"]
ENV["FL_PROJECT_TEAM_ID"] = ENV["TEAM_ID"]
ENV["FL_PROJECT_PROVISIONING_PROFILE_FILE"] = "adhoc.mobileprovision"
ENV["FL_CERTIFICATE_PATH"] = "cert.p12"

default_platform(:ios)

platform :ios do

  desc "Create IPA for AppStore submission"
  lane :build do
    clean_build_artifacts

    update_app_identifier(
      plist_path: "single/Info.plist"
    )
    update_project_team
    update_project_provisioning
    disable_automatic_code_signing

    build_app(
      scheme: "single",
      export_method: "ad-hoc",
      clean: true
    )
  end

  keychain_name = "ios-build.keychain"
  keychain_password = SecureRandom.base64

  lane :setup_certificate do
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    import_certificate(
      certificate_path: ENV["FL_CERTIFICATE_PATH"],
      certificate_password: ENV["FL_CERTIFICATE_PASSWORD"],
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
  end
end
